version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_dev
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_MAIL_SMTP_HOST', 'mailhog' );
        define( 'WP_MAIL_SMTP_PORT', 1025 );
    volumes:
      - wordpress_data:/var/www/html
      - ${WP_CONTENT_DIR}:/var/www/html/wp-content
    depends_on:
      - db
      - mailhog

  db:
    image: mysql:8.0
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "${MAILHOG_PORT}:8025"

  wpcli:
    image: wordpress:cli
    container_name: wpcli
    volumes:
      - wordpress_data:/var/www/html
      - ${WP_CONTENT_DIR}:/var/www/html/wp-content
    working_dir: /var/www/html
    entrypoint: ["wp"]
    depends_on:
      - wordpress
      - db

volumes:
  wordpress_data:
  db_data:
